[context.branch-deploy.environment]
  NEXT_PUBLIC_ARPETTE_URL = "https://api-test.tera-campus.com"
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID = "000000000000000"
  NEXT_PUBLIC_GA_ID = "UA-000000000-0"

[context.deploy-preview.environment]
  NEXT_PUBLIC_ARPETTE_URL = "https://api-test.tera-campus.com"
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID = "000000000000000"
  NEXT_PUBLIC_GA_ID = "UA-000000000-0"

[context.production.environment]
  NEXT_PUBLIC_ARPETTE_URL = "https://api.tera-campus.com"
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID = "351563326012968"
  NEXT_PUBLIC_GA_ID = "UA-191583607-1"
