[context.branch-deploy.environment]
  NEXT_PUBLIC_ARPETTE_URL = "https://api-test.tera-campus.com"
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID = "000000000000000"
  NEXT_PUBLIC_GA_ID = "UA-000000000-0"
  MONDAY_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjk4MTc3ODkwLCJ1aWQiOjE2NTA2ODYyLCJpYWQiOiIyMDIxLTAyLTAyVDE1OjAxOjI1LjAwMFoiLCJwZXIiOiJtZTp3cml0ZSIsImFjdGlkIjo3MjY5OTA1LCJyZ24iOiJ1c2UxIn0.sn9mlb7ZZwUcZzOLDDZ3SiL-r-PA5ofc4ySnxgmV_dE"
  MONDAY_CRM_STUDENTS_BOARD_ID = "1493476486"
  MONDAY_PLANNING_LIVES_BOARD_ID ="1201384641"
  MJ_APIKEY_PUBLIC = "00000000000000000000000000000000"
  MJ_APIKEY_PRIVATE = "00000000000000000000000000000000"


[context.deploy-preview.environment]
  NEXT_PUBLIC_ARPETTE_URL = "https://api-test.tera-campus.com"
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID = "000000000000000"
  NEXT_PUBLIC_GA_ID = "UA-000000000-0"
  MONDAY_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjk4MTc3ODkwLCJ1aWQiOjE2NTA2ODYyLCJpYWQiOiIyMDIxLTAyLTAyVDE1OjAxOjI1LjAwMFoiLCJwZXIiOiJtZTp3cml0ZSIsImFjdGlkIjo3MjY5OTA1LCJyZ24iOiJ1c2UxIn0.sn9mlb7ZZwUcZzOLDDZ3SiL-r-PA5ofc4ySnxgmV_dE"
  MONDAY_PLANNING_LIVES_BOARD_ID ="1201384641"
  MONDAY_CRM_STUDENTS_BOARD_ID = "1605134517"
  MJ_APIKEY_PUBLIC = "00000000000000000000000000000000"
  MJ_APIKEY_PRIVATE = "00000000000000000000000000000000"


[context.production.environment]
  NEXT_PUBLIC_ARPETTE_URL = "https://api.tera-campus.com"
  NEXT_PUBLIC_FACEBOOK_PIXEL_ID = "351563326012968"
  NEXT_PUBLIC_GA_ID = "UA-191583607-1"
  MONDAY_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJ0aWQiOjk4MTc3ODkwLCJ1aWQiOjE2NTA2ODYyLCJpYWQiOiIyMDIxLTAyLTAyVDE1OjAxOjI1LjAwMFoiLCJwZXIiOiJtZTp3cml0ZSIsImFjdGlkIjo3MjY5OTA1LCJyZ24iOiJ1c2UxIn0.sn9mlb7ZZwUcZzOLDDZ3SiL-r-PA5ofc4ySnxgmV_dE"
  MONDAY_CRM_STUDENTS_BOARD_ID = "1207981688"
  MONDAY_PLANNING_LIVES_BOARD_ID ="1201384641"
  MJ_APIKEY_PUBLIC = "48d2e070dea8c022ac354e9ece893e9b"
  MJ_APIKEY_PRIVATE = "8c1aaeb136affff680ee09b943dc317a"

